print("- Wake up")
print("- Get dressed")
print("- Brush")
print("- Do my hair")
print("- Eat breakfast")
print("- Go to school")
print("- Go to classes")
print("- Eat lunch")
print("- Go to rest of classes")
print("- Get on the bus")
print("- Get home")
print("- Get mail")
print("- Go inside")
print("- Have a snack")
print("- After-school activities")
print("- Do my homework")
print("- Call my friends")
print("- Eat dinner")
print("- Get ready for bed")
print("- Go to sleep")